apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler # 水平スケールを設定
metadata:
  name: hpa-demo
  namespace: demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: text-checker
  minReplicas: 3 # 最小Pod数
  maxReplicas: 10 # 最大Pod数
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 20
